name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Add GOBIN to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Publish Release
        shell: bash
        env:
          GITHUB_TOKEN:    ${{ secrets.RELEASE_TOKEN }}
        run: |
          git config --global user.name Julien4218
          git config --global user.email Julien4218@users.noreply.github.com
          make release
